### ISSUE TITLE
Treat about to expire tokens as expired

### ISSUE THREAD

**Issue by justin-gerhardt** [dermesser/yup-oauth2#78]
Authenticator::token either retrieves a new token or a cached one if it’s not expired. As it is responsible for refreshing tokens it is reasonable to assume any token it provides is fresh. However, if the cached token is going to imminently expire it is possible for it to provide a token that becomes useless before it can be used (either the client is too slow or the client and servers clocks are off). 

If instead it treats any cached token with say < 1 minute left on the lifespan as being already expired It doesn't meaningfully increase the number of refreshes but make it far more likely the token provided is actually useful.

**Comment by Byron** [comment]
Thanks, @justin-gerhardt , I would acknowledge and second this statement.

The reason this _seemingly_ wasn't a problem yet is that the prime user of yup-oauth2 is the [google-apis-rs](https://github.com/byron/google-apis-rs) has built-in logic to retry requests after refreshing the token if the requests failed due to an expired token.

However, I believe that adjusting the logic in yup-oauth2 can help any other client to not run into unnecessary trouble.
