### ISSUE TITLE
Clarification on hyper version regarding google apis

### ISSUE THREAD

**Issue by flxo** [dermesser/yup-oauth2#96]
Hi,

I have a question regarding the relation of versions of hyper and the google apis:
 
`yup-oauth2` claims the following:

```
Version 1.x for Hyper versions bellow 12 Version 2.x for Hyper versions 12 and above
```

The `google-apis-rs` currently [claim hyper 0.10]( https://github.com/Byron/google-apis-rs/blob/57a7ee37e583ca4b6db3c361d85591a84f92c861/gen/gmail1/Cargo.toml#L22)

Am I right that I cannot use `yup-oauth2` > 1.x in conjunction with one of the google apis crates in one crate since I would need different hyper versions?
The `yup-oauth2` examples all refer to v1.x and I think it's currently not possible to update them until `google-api-rs` is upgraded too. Correct me if I'm wrong.

There is a [open issues](https://github.com/Byron/google-apis-rs/issues/173) on updating `google-api-rs`.

Thanks!

@flxo

**Comment by markcatley** [comment]
Yes, if you want to use the `google-api-rs` then you'll need to stick with `yup-oauth2 = "^1.0.0"` and `hyper = 0.10`. Since `google-api-rs` depends on `yup-oauth2` this library needed to be upgraded first.

**Comment by flxo** [comment]
Thanks for the confirmation!

**Comment by dermesser** [comment]
Yes, this is an ugly wart right now :( The recent two iterations, 2.0 and 3.0, can't be used with `google-apis-rs` because they are not yet updated (to either hyper, or the futures API). See Byron/google-apis-rs/issues/189 -- I'm not quite qualified enough (respectively have enough time) to do the necessary changes, as the code used for generating the crates is not trivial; even though the changes to make it work with especially yup-oauth v3.0 should be relatively self-contained.
